apiVersion: builtin
kind: HelmChartInflationGenerator

metadata:
  name: traefik

name: traefik
# renovate: datasource=helm depName=traefik repository=https://traefik.github.io/charts
version: 41.2.0
releaseName: traefik
namespace: traefik
repo: https://traefik.github.io/charts
includeCRDs: true
valuesInline:
  providers:
    kubernetesGateway:
      enabled: true

  gateway:
    enabled: false

  gatewayClass:
    enabled: false

  api:
    insecure: true

  metrics:
    prometheus:
      service:
        enabled: true
      # Required as kustomize's helmchartinflationgenerator cannot see cluster CRDs
      disableAPICheck: true
      serviceMonitor:
        enabled: true
