apiVersion: builtin
kind: HelmChartInflationGenerator

metadata:
  name: traefik

name: traefik
# renovate: datasource=helm depName=traefik repository=https://traefik.github.io/charts
version: 40.3.0
releaseName: traefik
namespace: traefik
repo: https://traefik.github.io/charts
includeCRDs: true
valuesInline:
  providers:
    kubernetesGateway:
      enabled: true

  gateway:
    enabled: false

  gatewayClass:
    enabled: false

  api:
    insecure: true
