apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy

metadata:
  name: local-gateway-policy

spec:
  serviceSelector:
    matchLabels:
      app.kubernetes.io/name: traefik
  interfaces:
    - ^enp3s0$
  externalIPs: false
  loadBalancerIPs: true
