apiVersion: builtin
kind: HelmChartInflationGenerator

metadata:
  name: immich

name: immich
# renovate: datasource=docker depName=ghcr.io/immich-app/immich-charts/immich
version: 0.13.1
releaseName: immich
namespace: immich
repo: oci://ghcr.io/immich-app/immich-charts
includeCRDs: true
