apiVersion: builtin
kind: HelmChartInflationGenerator

metadata:
  name: jellyfin

name: jellyfin
# renovate: datasource=helm depName=jellyfin repository=https://jellyfin.github.io/jellyfin-helm
version: 3.2.0
releaseName: jellyfin
namespace: jellyfin
repo: https://jellyfin.github.io/jellyfin-helm
includeCRDs: true
valuesInline:
  persistence:
    config:
      enabled: true
      existingClaim: jellyfin-config
    media:
      enabled: true
      type: hostPath
      hostPath: /var/mnt/kubernetes-data/jellyfin/media
    cache:
      enabled: true
      type: hostPath
      hostPath: /var/mnt/kubernetes-data/jellyfin/cache
