apiVersion: builtin
kind: HelmChartInflationGenerator

metadata:
  name: jellyfin

name: jellyfin
# renovate: datasource=helm depName=jellyfin repository=https://jellyfin.github.io/jellyfin-helm
version: 3.2.0
releaseName: jellyfin
namespace: jellyfin
repo: https://jellyfin.github.io/jellyfin-helm
includeCRDs: true
valuesInline:
  persistence:
    config:
      enabled: true
      existingClaim: jellyfin-config
    media:
      enabled: true
      existingClaim: jellyfin-media

  livenessProbe:
    timeoutSeconds: 10
    failureThreshold: 20

  readinessProbe:
    timeoutSeconds: 10
    failureThreshold: 20

  volumes:
    - name: unraid-media
      nfs:
        server: homelab.knlim.dev
        path: /mnt/user/media

  volumeMounts:
    - name: unraid-media
      mountPath: /unraid-media
