apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: vikunja-secret
  namespace: vikunja

spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: vikunja-secret
    creationPolicy: Owner
  data:
    - secretKey: db-password
      remoteRef:
        key: postgres/vikunja_password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: jwt-secret
      remoteRef:
        key: vikunja/jwt_secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
