apiVersion: builtin
kind: HelmChartInflationGenerator

metadata:
  name: ollama

name: ollama
# renovate: datasource=helm depName=ollama repository=https://otwld.github.io/ollama-helm/
version: 1.79.0
releaseName: ollama
namespace: ollama
repo: https://otwld.github.io/ollama-helm/
includeCRDs: true
valuesInline:
  persistentVolume:
    enabled: true
