apiVersion: builtin
kind: HelmChartInflationGenerator

metadata:
  name: vikunja

valuesInline:
  vikunja:
    persistence:
      database:
        enabled: false
      data:
        size: 5Gi
        storageClass: local-data

    ingress:
      main:
        enabled: false

    env:
      VIKUNJA_DATABASE_TYPE: postgres
      VIKUNJA_DATABASE_HOST: postgres-rw.postgres.svc.cluster.local
      VIKUNJA_DATABASE_USER: vikunja
      VIKUNJA_DATABASE_DATABASE: vikunja
      VIKUNJA_SERVICE_PUBLICURL: "https://vikunja.neon-wyrm.ts.net"
      VIKUNJA_DATABASE_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: vikunja-secret
            key: db-password
      VIKUNJA_SERVICE_JWTSECRET:
        valueFrom:
          secretKeyRef:
            name: vikunja-secret
            key: jwt-secret
