apiVersion: builtin
kind: HelmChartInflationGenerator

metadata:
  name: vikunja

name: vikunja
# renovate: datasource=docker depName=ghcr.io/go-vikunja/helm-chart/vikunja
version: 2.3.0
releaseName: vikunja
namespace: vikunja
repo: oci://ghcr.io/go-vikunja/helm-chart
includeCRDs: true
