apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: webhook-aws-credentials
  namespace: cluster-services

spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: webhook/aws_access_key_id
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: webhook/aws_secret_access_key
