apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: mariadb-auth
  namespace: mariadb

spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: mariadb-auth
    creationPolicy: Owner
  data:
    - secretKey: mariadb-root-password
      remoteRef:
        key: mariadb/root_password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: mariadb-password
      remoteRef:
        key: mariadb/romm_password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
