apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: romm
  namespace: romm
  annotations:
    tailscale.com/tags: "tag:k8s-romm"

spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: romm
      port:
        number: 8080
  tls:
    - hosts:
        - romm
