apiVersion: v1
kind: PersistentVolume

metadata:
  name: romm-resources

spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""
  hostPath:
    path: /var/mnt/kubernetes-data/romm/resources
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume

metadata:
  name: romm-config

spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""
  hostPath:
    path: /var/mnt/kubernetes-data/romm/config
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume

metadata:
  name: romm-assets

spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""
  hostPath:
    path: /var/mnt/kubernetes-data/romm/assets
    type: DirectoryOrCreate
