apiVersion: v1
kind: PersistentVolume

metadata:
  name: romm-resources

spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /var/mnt/kubernetes-array/romm/resources
    type: DirectoryOrCreate
