apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: romm-resources
  namespace: romm

spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-data
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: romm-config
  namespace: romm

spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-data
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: romm-assets
  namespace: romm

spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-array
  resources:
    requests:
      storage: 5Gi
