apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: otterwiki-deploy-key
  namespace: otterwiki

spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: otterwiki-deploy-key
    creationPolicy: Owner
  data:
    - secretKey: ssh-privatekey
      remoteRef:
        key: otterwiki/private_key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
