apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../bases/otterwiki
  - cronjob-sync.yaml
  - externalsecret-config.yaml
  - externalsecret-deploy-key.yaml
  - ingress.yaml

patches:
  - path: patch-deployment.yaml

images:
  - name: alpine/git
    newTag: "v2.54.0"
  - name: redimp/otterwiki
    newTag: "2.24.0"
