apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: environment-variables
  namespace: argo-workflows

spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
  data:
    # 1Password
    - secretKey: OP_SERVICE_ACCOUNT_TOKEN
      remoteRef:
        key: op-sa-terraform/credential

    # ArgoCD
    - secretKey: ARGOCD_AUTH_TOKEN
      remoteRef:
        key: argocd/credential
    - secretKey: ARGOCD_SERVER
      remoteRef:
        key: argocd/url

    # AWS
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: terraform-aws/aws_access_key_id
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: terraform-aws/aws_secret_access_key

    # Cloudflare
    - secretKey: CLOUDFLARE_API_TOKEN
      remoteRef:
        key: cloudflare-knlim.dev/credential

    # Discord
    - secretKey: ARGO_WORKFLOWS_URL
      remoteRef:
        key: discord/argo_workflows_url
    - secretKey: DISCORD_WEBHOOK_URL
      remoteRef:
        key: discord/webhook_url

    # Grafana
    - secretKey: GRAFANA_AUTH
      remoteRef:
        key: terraform-grafana/credential
    - secretKey: GRAFANA_URL
      remoteRef:
        key: terraform-grafana/url

    # Terraform
    - secretKey: TG_BUCKET
      remoteRef:
        key: terraform-aws/bucket
