apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: cloudnative-pg
    # renovate: datasource=helm depName=cloudnative-pg repository=https://cloudnative-pg.github.io/charts
    version: 0.29.0
    repo: https://cloudnative-pg.github.io/charts
    releaseName: cloudnative-pg
    namespace: postgres
    includeCRDs: true
