apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: immich-db-secret
  namespace: immich

spec:
  refreshInterval: 24h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: immich-db-secret
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: postgres/immich_password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
