apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
  - helm-values

resources:
  - externalsecret.yaml
  - generated/httproute.yaml
  - ingress.yaml
  - namespace.yaml
  - pvc.yaml
