apiVersion: v1
kind: PersistentVolume

metadata:
  name: immich-library

spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /var/mnt/media/images
    type: Directory
  claimRef:
    name: immich-library
    namespace: immich
---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: immich-library
  namespace: immich

spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: immich-library
  resources:
    requests:
      storage: 10Ti
---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: immich-ml-cache
  namespace: immich

spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-data
  resources:
    requests:
      storage: 10Gi
