apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: argo-events-webhook
  namespace: argo-workflows

subjects:
  - kind: ServiceAccount
    name: argo-events-webhook
    namespace: cluster-services

roleRef:
  kind: Role
  name: argo-events-webhook
  apiGroup: rbac.authorization.k8s.io
