apiVersion: argoproj.io/v1alpha1
kind: Sensor

metadata:
  name: webhook
  namespace: cluster-services

spec:
  template:
    serviceAccountName: argo-events-webhook

  dependencies:
    - name: sqs-dep
      eventSourceName: webhook
      eventName: homelab-ci

  triggers:
    - template:
        name: submit-ci-workflow
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: ci-
                namespace: argo-workflows
              spec:
                workflowTemplateRef:
                  name: ci
                arguments:
                  parameters:
                    - name: repo
                      value: ""
                    - name: branch
                      value: ""
                    - name: before
                      value: ""
                    - name: after
                      value: ""
                    - name: paths
                      value: ""
      parameters:
        - src:
            dependencyName: sqs-dep
            dataKey: repo
          dest: spec.arguments.parameters.0.value
        - src:
            dependencyName: sqs-dep
            dataKey: ref
          dest: spec.arguments.parameters.1.value
        - src:
            dependencyName: sqs-dep
            dataKey: before
          dest: spec.arguments.parameters.2.value
        - src:
            dependencyName: sqs-dep
            dataKey: after
          dest: spec.arguments.parameters.3.value
        - src:
            dependencyName: sqs-dep
            dataKey: body.paths
            useDefault: true
            default: ""
          dest: spec.arguments.parameters.4.value
