apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: jellyfin-config
  namespace: jellyfin

spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 2Gi
  volumeName: jellyfin-config
