apiVersion: postgresql.cnpg.io/v1
kind: Cluster

metadata:
  name: postgres
  namespace: postgres
  annotations:
    argocd.argoproj.io/sync-wave: "1"

spec:
  instances: 1
  storage:
    size: 50Gi
    storageClass: local-data
  imageName: ghcr.io/cloudnative-pg/postgresql:18-standard-trixie
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
    extensions:
      - name: vchord
        image:
          reference: ghcr.io/tensorchord/vchord-scratch:pg18-v1.1.1
        dynamic_library_path:
          - /usr/lib/postgresql/18/lib
        extension_control_path:
          - /usr/share/postgresql/18/
  managed:
    roles:
      - name: immich
        ensure: present
        login: true
        inherit: true
        connectionLimit: -1
        passwordSecret:
          name: postgres-immich-password
