apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate

metadata:
  name: ci
  namespace: argo-workflows

spec:
  entrypoint: main
  onExit: status
  synchronization:
    mutexes:
      - name: "ci-{{workflow.parameters.repo}}"
  ttlStrategy:
    secondsAfterCompletion: 86400
  activeDeadlineSeconds: 3600
  serviceAccountName: argo-workflow
  arguments:
    parameters:
      - name: branch
        value: main
      - name: repo
        value: git@github.com:kn-lim/homelab.git
      - name: before
        value: ""
      - name: after
        value: ""
      - name: paths
        value: ""

  volumes:
    - name: ssh-key
      secret:
        secretName: argo-workflows-ssh-key
        defaultMode: 0400

  volumeClaimTemplates:
    - metadata:
        name: workdir
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi

  templates:
    - name: main
      dag:
        tasks:
          - name: git-clone
            templateRef:
              name: git
              template: clone
            arguments:
              parameters:
                - name: repo
                  value: "{{workflow.parameters.repo}}"
                - name: branch
                  value: "{{workflow.parameters.branch}}"
          - name: changes
            dependencies: [git-clone]
            templateRef:
              name: command
              template: changes
            arguments:
              parameters:
                - name: before
                  value: "{{workflow.parameters.before}}"
                - name: after
                  value: "{{workflow.parameters.after}}"
                - name: paths
                  value: "{{workflow.parameters.paths}}"
          - name: parse
            dependencies: [changes]
            templateRef:
              name: command
              template: parse
            arguments:
              parameters:
                - name: paths
                  value: "{{tasks.changes.outputs.result}}"
          - name: apply
            dependencies: [parse]
            withParam: "{{tasks.parse.outputs.result}}"
            templateRef:
              name: command
              template: run
            arguments:
              parameters:
                - name: command
                  value: "{{item.command}}"

    - name: status
      steps:
        - - name: send-status
            templateRef:
              name: discord
              template: status
