apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate

metadata:
  name: command
  namespace: argo-workflows

spec:
  templates:
    - name: run
      inputs:
        parameters:
          - name: command
          - name: workdir
            default: /workdir/src
      container:
        image: ghcr.io/kn-lim/toolbox
        command: [bash, -c]
        args:
          - |
            {{inputs.parameters.command}}
        workingDir: "{{inputs.parameters.workdir}}"
        envFrom:
          - secretRef:
              name: environment-variables
        volumeMounts:
          - name: workdir
            mountPath: /workdir

    - name: parse
      inputs:
        parameters:
          - name: paths
      script:
        image: ghcr.io/kn-lim/toolbox
        command: [bash]
        source: |
          task ci:parse PATHS="{{inputs.parameters.paths}}"
        workingDir: /workdir/src
        envFrom:
          - secretRef:
              name: environment-variables
        volumeMounts:
          - name: workdir
            mountPath: /workdir
