apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate

metadata:
  name: command
  namespace: argo-workflows

spec:
  volumes:
    - name: ssh-key
      secret:
        secretName: argo-workflows-ssh-key
        defaultMode: 0400

  templates:
    - name: run
      inputs:
        parameters:
          - name: command
          - name: workdir
            default: /workdir/src
      container:
        image: ghcr.io/jdx/mise
        command: [bash, -c]
        args:
          - |
            mise trust &&
            eval "$(mise activate bash)" &&
            {{inputs.parameters.command}}
        workingDir: "{{inputs.parameters.workdir}}"
        env:
          - name: MISE_CACHE_DIR
            value: /workdir/.cache/mise
          - name: MISE_DATA_DIR
            value: /workdir/.mise
          - name: GIT_SSH_COMMAND
            value: "ssh -i /ssh/sshPrivateKey -o StrictHostKeyChecking=no"
        envFrom:
          - secretRef:
              name: environment-variables
        volumeMounts:
          - name: workdir
            mountPath: /workdir
          - name: ssh-key
            mountPath: /ssh
            readOnly: true
