apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate

metadata:
  name: git
  namespace: argo-workflows

spec:
  templates:
    - name: clone
      inputs:
        parameters:
          - name: repo
          - name: branch
            default: main
      container:
        image: ghcr.io/kn-lim/toolbox
        command: [sh, -c]
        args:
          - |
            mkdir -p /workdir/.ssh
            cp /etc/ssh-key/sshPrivateKey /workdir/.ssh/id_rsa
            chmod 600 /workdir/.ssh/id_rsa
            GIT_SSH_COMMAND='ssh -i /workdir/.ssh/id_rsa -o StrictHostKeyChecking=no' \
            git clone --branch "{{inputs.parameters.branch}}" "{{inputs.parameters.repo}}" /workdir/src
        volumeMounts:
          - name: workdir
            mountPath: /workdir
          - name: ssh-key
            mountPath: /etc/ssh-key
            readOnly: true
