apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ci.yaml
  - command.yaml
  - discord.yaml
  - git.yaml

configurations:
  - configurations.yaml

images:
  - name: ghcr.io/kn-lim/toolbox
    newTag: "1.2.1"
