apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate

metadata:
  name: setup
  namespace: argo-workflows

spec:
  templates:
    - name: setup
      inputs:
        parameters:
          - name: repo
          - name: revision
            default: main
        artifacts:
          - name: source
            path: /workdir/src
            git:
              repo: "{{inputs.parameters.repo}}"
              revision: "{{inputs.parameters.revision}}"
              depth: 1
      container:
        image: ghcr.io/jdx/mise
        command: [bash, -c]
        args:
          - |
            mise trust &&
            mise install
        workingDir: "/workdir/src"
        env:
          - name: MISE_CACHE_DIR
            value: /workdir/.cache/mise
          - name: MISE_DATA_DIR
            value: /workdir/.mise
        volumeMounts:
          - name: workdir
            mountPath: /workdir
