apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate

metadata:
  name: setup
  namespace: argo-workflows

spec:
  templates:
    - name: setup
      container:
        image: ghcr.io/jdx/mise
        command: [bash, -c]
        args:
          - |
            mise trust &&
            mise install \
              aqua:argoproj/argo-cd \
              aqua:go-task/task \
              aqua:gruntwork-io/terragrunt \
              aqua:hashicorp/terraform \
              aqua:mikefarah/yq \
              aqua:pre-commit/pre-commit
        workingDir: "/workdir/src"
        env:
          - name: MISE_CACHE_DIR
            value: /workdir/.cache/mise
          - name: MISE_DATA_DIR
            value: /workdir/.mise
        volumeMounts:
          - name: workdir
            mountPath: /workdir
