apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: argocd-tsidp
  namespace: argocd

spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: argocd-tsidp
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: client_id
      remoteRef:
        key: tsidp-argocd/client_id
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: client_secret
      remoteRef:
        key: tsidp-argocd/client_secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
