apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
  - helm-values

resources:
  # - ../../../bases/argo-workflows
  - ingress.yaml
  - serviceaccount.yaml
  - secret-environment.yaml
  - secret-ssh.yaml
