apiVersion: builtin
kind: HelmChartInflationGenerator

metadata:
  name: prometheus

valuesInline:
  server:
    persistentVolume:
      enabled: true
      storageClass: local-data
      size: 10Gi

  alertmanager:
    enabled: false
