apiVersion: builtin
kind: HelmChartInflationGenerator

metadata:
  name: prometheus

valuesInline:
  server:
    storagePath: /var/mnt/kubernetes-data/prometheus
    persistentVolume:
      enabled: false
    extraVolumes:
      - name: prometheus-data
        hostPath:
          path: /var/mnt/kubernetes-data/prometheus
          type: DirectoryOrCreate
    extraVolumeMounts:
      - name: prometheus-data
        mountPath: /var/mnt/kubernetes-data/prometheus

  alertmanager:
    enabled: false
