apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: mariadb
    repo: https://charts.bitnami.com/bitnami
    version: 26.1.3
    releaseName: mariadb
    namespace: mariadb
    includeCRDs: true
    valuesInline:
      architecture: standalone

      auth:
        existingSecret: mariadb-auth
        database: romm
        username: romm-user

      primary:
        persistence:
          enabled: true
          storageClass: local-data
          size: 10Gi
        resources:
          limits:
            memory: 512Mi
            cpu: 500m
          requests:
            memory: 256Mi
            cpu: 100m
