apiVersion: builtin
kind: HelmChartInflationGenerator

metadata:
  name: democratic-csi

name: democratic-csi
# renovate: datasource=helm depName=democratic-csi repository=https://democratic-csi.github.io/charts/
version: 0.15.1
repo: https://democratic-csi.github.io/charts/
includeCRDs: false

valuesInline:
  csiDriver:
    attachRequired: false
    fsGroupPolicy: File
    storageCapacity: true

  controller:
    strategy: node
    driver:
      image:
        # renovate: datasource=docker depName=ghcr.io/democratic-csi/democratic-csi
        tag: v1.9.5
    externalAttacher:
      enabled: false
    externalResizer:
      enabled: false
    externalSnapshotter:
      enabled: false
    externalProvisioner:
      extraArgs:
        - --leader-election=false
        - --node-deployment=true
        - --node-deployment-immediate-binding=true
        - --feature-gates=Topology=true
        - --strict-topology=true
        - --enable-capacity=true
        - --capacity-ownerref-level=1

  node:
    driver:
      image:
        # renovate: datasource=docker depName=ghcr.io/democratic-csi/democratic-csi
        tag: v1.9.5

  driver:
    config:
      driver: local-hostpath
      local-hostpath:
        dirPermissionsMode: "0777"
        dirPermissionsUser: 0
        dirPermissionsGroup: 0
