# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  # TODO: Remove --force if no longer a single node cluster
  upgrade:
    desc: Upgrade talos to specified version
    requires:
      vars: [NODE_IP, VERSION]
    cmds:
      - |
        INSTALL_IMAGE=$(talosctl get machineconfig --nodes {{.NODE_IP}} -o yaml | yq 'select(di==0) | .spec | from_yaml | .machine.install.image')
        talosctl upgrade --nodes {{.NODE_IP}} --image "${INSTALL_IMAGE%:*}:v{{.VERSION}}" --force
