apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: open-webui-secret
  namespace: open-webui

spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: open-webui-secret
    creationPolicy: Owner
  data:
    - secretKey: webui-secret-key
      remoteRef:
        key: open-webui/webui_secret_key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
