apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generators:
  - helm-values

resources:
  - ../../../bases/open-webui
  - namespace.yaml
  - pv.yaml
  - externalsecret.yaml
  - ingress.yaml
  - generated/httproute.yaml
