apiVersion: v1
kind: PersistentVolume

metadata:
  name: ollama-models

spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""
  hostPath:
    path: /var/mnt/kubernetes-vm/ollama/models
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume

metadata:
  name: open-webui-data

spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""
  hostPath:
    path: /var/mnt/kubernetes-data/open-webui/data
    type: DirectoryOrCreate
