apiVersion: builtin
kind: HelmChartInflationGenerator

metadata:
  name: jellyfin

valuesInline:
  jellyfin:
    env:
      - name: JELLYFIN_PublishedServerUrl
        value: "https://jellyfin.knlim.dev"
  resources:
    limits:
      nvidia.com/gpu: 1

  persistence:
    media:
      enabled: true
      type: hostPath
      hostPath: /var/mnt/media
    cache:
      enabled: true
      type: pvc
      storageClass: local-data
      size: 20Gi
      accessMode: ReadWriteOnce
