apiVersion: builtin
kind: HelmChartInflationGenerator

metadata:
  name: jellyfin

valuesInline:
  jellyfin:
    env:
      - name: JELLYFIN_PublishedServerUrl
        value: "https://jellyfin.knlim.dev"
  resources:
    limits:
      nvidia.com/gpu: 1

  persistence:
    media:
      enabled: true
      type: hostPath
      hostPath: /var/mnt/kubernetes-array/jellyfin/media
    cache:
      enabled: true
      type: pvc
      storageClass: local-data
      size: 50Gi
      accessMode: ReadWriteOnce

  volumes:
    - name: unraid-media
      nfs:
        server: "homelab.knlim.dev"
        path: /mnt/user/media

  volumeMounts:
    - name: unraid-media
      mountPath: /unraid-media
