apiVersion: builtin
kind: HelmChartInflationGenerator

metadata:
  name: jellyfin

valuesInline:
  jellyfin:
    env:
      - name: JELLYFIN_PublishedServerUrl
        value: "https://jellyfin.knlim.dev"
  resources:
    limits:
      nvidia.com/gpu: 1

  volumes:
    - name: unraid-media
      nfs:
        server: "homelab.knlim.dev"
        path: /mnt/user/media

  volumeMounts:
    - name: unraid-media
      mountPath: /unraid-media
