apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml

images:
  - name: adguard/adguardhome
    newTag: v0.107.78
  - name: tailscale/tailscale
    newTag: v1.102.3
