apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: kube-state-metrics
  namespace: prometheus

spec:
  # Community dashboards/rules expect job="kube-state-metrics"
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
  endpoints:
    - port: http
      honorLabels: true
