# https://docs.siderolabs.com/kubernetes-guides/monitoring-and-observability/deploy-metrics-server

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kubelet-serving-cert-approver

resources:
  - github.com/alex1989hu/kubelet-serving-cert-approver/deploy/standalone?ref=v0.11.0

patches:
  - target:
      kind: RoleBinding
      name: events:kubelet-serving-cert-approver
    patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: kubelet-serving-cert-approver
