apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate

metadata:
  name: command
  namespace: argo-workflows

spec:
  templates:
    - name: changes
      inputs:
        parameters:
          - name: before
            default: ""
          - name: after
            default: ""
          - name: paths
            default: ""
      script:
        image: alpine/git
        command: [sh]
        source: |
          if [ -n "{{inputs.parameters.paths}}" ]; then
            echo "{{inputs.parameters.paths}}"
          else
            git diff --name-only {{inputs.parameters.before}} {{inputs.parameters.after}} | tr '\n' ',' | sed 's/,$//'
          fi
        workingDir: /workdir/src
        volumeMounts:
          - name: workdir
            mountPath: /workdir

    - name: parse
      inputs:
        parameters:
          - name: paths
      outputs:
        parameters:
          - name: targets
            valueFrom:
              path: /tmp/targets.txt
              default: ""
            globalName: ci-targets
      script:
        image: ghcr.io/kn-lim/homelab-ci
        imagePullPolicy: Always
        command: [bash]
        source: |
          set -eo pipefail
          task --yes --list > /dev/null
          task ci:parse PATHS="{{inputs.parameters.paths}}" | tee /tmp/commands.json
          jq -r '[.[].command | (capture("(APPLICATION|DIRECTORY)=(?<v>[^ ]+)") | .v)?] | join(", ")' \
            /tmp/commands.json > /tmp/targets.txt 2>/dev/null || : > /tmp/targets.txt
        workingDir: /workdir/src
        envFrom:
          - secretRef:
              name: environment-variables
        volumeMounts:
          - name: workdir
            mountPath: /workdir

    - name: run
      inputs:
        parameters:
          - name: command
          - name: workdir
            default: /workdir/src
      container:
        image: ghcr.io/kn-lim/homelab-ci
        imagePullPolicy: Always
        command: [bash, -c]
        args:
          - |
            set -eo pipefail
            task --yes --list > /dev/null
            {{inputs.parameters.command}}
        workingDir: "{{inputs.parameters.workdir}}"
        env:
          - name: AWS_REGION
            value: "us-west-2"
        envFrom:
          - secretRef:
              name: environment-variables
        volumeMounts:
          - name: workdir
            mountPath: /workdir
