apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate

metadata:
  name: git
  namespace: argo-workflows

spec:
  templates:
    - name: clone
      inputs:
        parameters:
          - name: repo
          - name: branch
            default: main
        artifacts:
          - name: source
            path: /workdir/src
            git:
              repo: "git@github.com:{{inputs.parameters.repo}}.git"
              revision: "{{inputs.parameters.branch}}"
              sshPrivateKeySecret:
                name: argo-workflows-ssh-key
                key: sshPrivateKey
              insecureIgnoreHostKey: true
      container:
        image: busybox
        command: [sh, -c]
        args: ["ls /workdir/src"]
        volumeMounts:
          - name: workdir
            mountPath: /workdir
