# This Service sends remote-write traffic to the Prometheus on the homelab cluster.
apiVersion: v1
kind: Service

metadata:
  annotations:
    tailscale.com/tailnet-fqdn: prometheus.neon-wyrm.ts.net
    tailscale.com/hostname: prometheus-egress-homelab-lenovo
  name: prometheus-egress
  namespace: alloy

spec:
  externalName: placeholder   # will be overwritten by operator
  type: ExternalName
